# Generated by Django 5.1.1 on 2024-11-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_productos', '0002_proveedor_producto_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='renta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('numero', models.IntegerField()),
                ('categoria', models.TextField(max_length=40)),
            ],
        ),
    ]
